#config_version=6

ball_devices:

  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: true

  bd_trough:
    ballswitches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5, s_trough_6, s_trough_jam
    eject_coil: c_trough_eject
    eject_targets: bd_pluger
    tags: trough, home, drain